# Generated by Django 4.2.3 on 2023-07-10 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_alter_productimage_options_remove_product_author_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="principal",
            field=models.BooleanField(default=False),
        ),
    ]
