# Generated by Django 4.2.3 on 2023-07-10 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_product_principal"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="marque",
            field=models.CharField(default="none", max_length=255),
        ),
    ]
