# Generated by Django 2.0 on 2024-02-20 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_product_mintime'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='paylink',
            field=models.CharField(default='none', max_length=255),
        ),
    ]
